<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130306180252 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE WorkHistory CHANGE feedback_received feedback_received VARCHAR(500) DEFAULT NULL, CHANGE reflection reflection VARCHAR(2000) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE WorkHistory CHANGE feedback_received feedback_received VARCHAR(255) DEFAULT NULL, CHANGE reflection reflection VARCHAR(255) DEFAULT NULL");
    }
}
