<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130128042253 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE About CHANGE address address VARCHAR(255) DEFAULT NULL, CHANGE location location VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE GeneralSettings ADD analytics VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE ProjectHistory CHANGE process process VARCHAR(3000) DEFAULT NULL, CHANGE feedback_received feedback_received VARCHAR(500) DEFAULT NULL, CHANGE reflection reflection VARCHAR(2000) DEFAULT NULL, CHANGE meta_description meta_description VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE WorkHistory CHANGE duties duties VARCHAR(255) DEFAULT NULL, CHANGE feedback_received feedback_received VARCHAR(255) DEFAULT NULL, CHANGE reflection reflection VARCHAR(255) DEFAULT NULL, CHANGE employer_phone_number employer_phone_number VARCHAR(255) DEFAULT NULL, CHANGE meta_description meta_description VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE About CHANGE address address VARCHAR(255) NOT NULL, CHANGE location location VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE GeneralSettings DROP analytics");
        $this->addSql("ALTER TABLE ProjectHistory CHANGE process process VARCHAR(3000) NOT NULL, CHANGE feedback_received feedback_received VARCHAR(500) NOT NULL, CHANGE reflection reflection VARCHAR(2000) NOT NULL, CHANGE meta_description meta_description VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE WorkHistory CHANGE duties duties VARCHAR(255) NOT NULL, CHANGE feedback_received feedback_received VARCHAR(255) NOT NULL, CHANGE reflection reflection VARCHAR(255) NOT NULL, CHANGE employer_phone_number employer_phone_number VARCHAR(255) NOT NULL, CHANGE meta_description meta_description VARCHAR(255) NOT NULL");
    }
}
