<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130812132254 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Education ADD row_order INT NOT NULL");
        $this->addSql("ALTER TABLE Navigation CHANGE navigation_order row_order INT NOT NULL");
        $this->addSql("ALTER TABLE ProjectHistory ADD row_order INT NOT NULL");
        $this->addSql("ALTER TABLE Skills ADD row_order INT NOT NULL");
        $this->addSql("ALTER TABLE WorkHistory ADD row_order INT NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Education DROP row_order");
        $this->addSql("ALTER TABLE Navigation CHANGE row_order navigation_order INT NOT NULL");
        $this->addSql("ALTER TABLE ProjectHistory DROP row_order");
        $this->addSql("ALTER TABLE Skills DROP row_order");
        $this->addSql("ALTER TABLE WorkHistory DROP row_order");
    }
}
