<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121111043312 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE About (id INT AUTO_INCREMENT NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, age INT NOT NULL, bio VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, interests_hobbies VARCHAR(255) DEFAULT NULL, email_address VARCHAR(255) NOT NULL, twitter VARCHAR(255) DEFAULT NULL, facebook VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Education (id INT AUTO_INCREMENT NOT NULL, education_institute VARCHAR(255) NOT NULL, qualification VARCHAR(255) NOT NULL, start_date DATE NOT NULL, duration NUMERIC(10, 0) NOT NULL, result VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE GeneralSettings (id INT AUTO_INCREMENT NOT NULL, portfolio_title VARCHAR(255) NOT NULL, display_subtitle TINYINT(1) NOT NULL, portfolio_subtitle VARCHAR(255) NOT NULL, display_logo TINYINT(1) NOT NULL, path VARCHAR(255) DEFAULT NULL, global_general_meta_title VARCHAR(255) NOT NULL, about_meta_title VARCHAR(255) NOT NULL, education_meta_title VARCHAR(255) NOT NULL, work_history_meta_title VARCHAR(255) NOT NULL, project_history_meta_title VARCHAR(255) NOT NULL, global_work_history_meta_title VARCHAR(255) NOT NULL, global_project_history_meta_title VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Image (id INT AUTO_INCREMENT NOT NULL, project_history_id INT DEFAULT NULL, image_title VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, updated DATETIME NOT NULL, INDEX IDX_4FC2B5B6A3FF60 (project_history_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Navigation (id INT AUTO_INCREMENT NOT NULL, navigation_order INT NOT NULL, href VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, alt VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE ProjectHistory (id INT AUTO_INCREMENT NOT NULL, project_name VARCHAR(255) NOT NULL, project_description VARCHAR(2000) NOT NULL, role VARCHAR(255) NOT NULL, process VARCHAR(3000) NOT NULL, feedback_received VARCHAR(500) NOT NULL, reflection VARCHAR(2000) NOT NULL, url VARCHAR(255) DEFAULT NULL, updated DATETIME NOT NULL, meta_title VARCHAR(255) NOT NULL, meta_description VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Skills (id INT AUTO_INCREMENT NOT NULL, skill_name VARCHAR(255) NOT NULL, competency VARCHAR(255) NOT NULL, years_experience NUMERIC(10, 0) NOT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE User (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE WorkHistory (id INT AUTO_INCREMENT NOT NULL, employer_name VARCHAR(255) NOT NULL, employer_address VARCHAR(255) NOT NULL, start_date DATE NOT NULL, duration NUMERIC(10, 0) NOT NULL, role VARCHAR(255) NOT NULL, duties VARCHAR(255) NOT NULL, feedback_received VARCHAR(255) NOT NULL, reflection VARCHAR(255) NOT NULL, employer_phone_number VARCHAR(255) NOT NULL, meta_title VARCHAR(255) NOT NULL, meta_description VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Image ADD CONSTRAINT FK_4FC2B5B6A3FF60 FOREIGN KEY (project_history_id) REFERENCES ProjectHistory (id)");

        // Insert the General Settings, without this the frontend doesnt run
        $this->addSql('INSERT INTO `GeneralSettings` VALUES (1, \'My Portfolio\', 0, \'Subtitle\', 0, null, \'My Portfolio\', \'About |\', \'Education |\', \'Work History |\', \'Project History |\', \'Work Case Study |\', \'Project Case Study |\' );');
        // Insert the Admin user, this allows the backend to be accessed
        $this->addSql('INSERT INTO `User` VALUES (1, \'admin\', \'5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8\');');
        // Insert the About data, this is information used by the backend and some of the frontend pages
        $this->addSql('INSERT INTO `About` VALUES (1, \'Mr Admin\', \'Pants\', \'25\', \'Blah\', \'Moonbase\', \'The moon!\', null, \'adminpants@adminpants.com\', null, null);');
        
        // Insert the Navigation data, this creates the navigation to go to all the available frontend pages
        $this->addSql('INSERT INTO `Navigation` VALUES (1, 1, \'/\', \'Home\', \'Home Link\');');
        $this->addSql('INSERT INTO `Navigation` VALUES (2, 2, \'/Education\', \'Education\', \'Education Link\');');
        $this->addSql('INSERT INTO `Navigation` VALUES (3, 3, \'/WorkHistory\', \'Work History\', \'Work History Link\');');
        $this->addSql('INSERT INTO `Navigation` VALUES (4, 4, \'/ProjectHistory\', \'Project History\', \'Project History Link\');');
        $this->addSql('INSERT INTO `Navigation` VALUES (5, 5, \'/About\', \'About\', \'About Link\');');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Image DROP FOREIGN KEY FK_4FC2B5B6A3FF60");
        $this->addSql("DROP TABLE About");
        $this->addSql("DROP TABLE Education");
        $this->addSql("DROP TABLE GeneralSettings");
        $this->addSql("DROP TABLE Image");
        $this->addSql("DROP TABLE Meta");
        $this->addSql("DROP TABLE Navigation");
        $this->addSql("DROP TABLE ProjectHistory");
        $this->addSql("DROP TABLE Skills");
        $this->addSql("DROP TABLE User");
        $this->addSql("DROP TABLE WorkHistory");
    }
}
