<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130827181942 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE File (id INT AUTO_INCREMENT NOT NULL, file_type VARCHAR(255) NOT NULL, original_filename VARCHAR(255) NOT NULL, filename VARCHAR(255) NOT NULL,  file_title VARCHAR(255) NOT NULL, entity_name VARCHAR(255) NOT NULL, entity_id INT NOT NULL, description VARCHAR(255) NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("DROP TABLE image");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE image (id INT AUTO_INCREMENT NOT NULL, project_history_id INT DEFAULT NULL, image_title VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, updated DATETIME NOT NULL, INDEX IDX_4FC2B5B6A3FF60 (project_history_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE image ADD CONSTRAINT FK_4FC2B5B6A3FF60 FOREIGN KEY (project_history_id) REFERENCES ProjectHistory (id)");
        $this->addSql("DROP TABLE File");
    }
}
