<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130805113830 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ProjectHistory CHANGE feedback_received feedback_received VARCHAR(2000) DEFAULT NULL");
        $this->addSql("ALTER TABLE WorkHistory ADD end_date DATE NOT NULL, DROP duration, CHANGE duties duties VARCHAR(2500) DEFAULT NULL, CHANGE feedback_received feedback_received VARCHAR(2000) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ProjectHistory CHANGE feedback_received feedback_received VARCHAR(500) DEFAULT NULL");
        $this->addSql("ALTER TABLE WorkHistory ADD duration NUMERIC(10, 0) NOT NULL, DROP end_date, CHANGE duties duties VARCHAR(255) DEFAULT NULL, CHANGE feedback_received feedback_received VARCHAR(500) DEFAULT NULL");
    }
}
